# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="/root/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="xiong-chiamiov"
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=( git 
          zsh-autosuggestions
          zsh-syntax-highlighting
        )

source $ZSH/oh-my-zsh.sh

# User configuration

# starship
eval "$(starship init zsh)"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export GIT_EDITOR=vim
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# =================================================================
# wsl configuration
# =================================================================

function set-wsl-proxy() {
  local host_ip
  host_ip=$(ip route | grep '^default' | awk '{print $3}')

  if [[ -z "$host_ip" ]]; then
    echo "❌ 无法获取宿主机 IP。"
    return 1
  fi

  export http_proxy="http://${host_ip}:7890"
  export https_proxy="http://${host_ip}:7890"

  echo "✅ 代理已设置:"
  echo "http_proxy=$http_proxy"
  echo "https_proxy=$https_proxy"
}

function unset-wsl-proxy() {
  unset http_proxy
  unset https_proxy
  echo "🧹 已清除代理设置。"
}

if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
  alias e="powershell.exe start explorer.exe ."
  alias setproxy=set-wsl-proxy
  alias usetproxy=unset-wsl-proxy
fi


## 通用配置
alias vim="nvim"
alias lg="lazygit"

if [ -d "/root/bin" ] ; then
  for dir in /root/bin/*/ ; do
    export PATH=$PATH:$dir
  done
fi

alias docker-clean-none='docker rmi $(docker images -f "dangling=true" -q)'

# 默认显示 icons： 
alias ls="exa"
# 显示文件目录详情
alias ll="exa --icons --long --header"
# 显示全部文件目录，包括隐藏文件
alias la="exa --icons --long --header --all"
# 显示详情的同时，附带 git 状态信息
alias lg="exa --icons --long --header --all --git"
# 替换 tree 命令
alias tree="exa --tree --icons"
export EXA_COLORS="\
di=34:\
ln=36:\
ex=32:\
*.c=0:\
*.h=0:\
*.S=0:\
*.ld=0"

glogf() {
  local file="$1"

  if [[ -z "$file" ]]; then
    echo "Usage: glogf <file>"
    return 1
  fi

  git log --all \
    --date=short \
    --pretty=format:"\
%C(bold yellow)%h%C(reset)  \
%C(green)%ad%C(reset)  \
%C(cyan)%<(12,trunc)%an%C(reset)  \
%C(white)%<(60,trunc)%s%C(reset)" \
    -- "$file" \
  | fzf --ansi \
      --delimiter=" " \
      --preview "git -c core.pager=cat --no-pager show --color=always {1} -- \"$file\"" \
      --preview-window=right:70%
}

# if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
    # tmux attach -t default || tmux new -s default
# fi
# source /opt/esp/entrypoint.sh
# export LANG=en_US.UTF-8
# export LC_ALL=en_US.UTF-8
